### PR TITLE
Fix descriptors copy

### LINKED ISSUE #20: This changes whether a property is writable or configurable
The new properties returned by this library are always writable and configurable, even when the original properties were not. While non-writable or non-configurable properties are sometimes problematic, there are sometimes legitimate reasons for it. This seems to be an unintentional side effect.

```js
const obj = Object.defineProperty({}, 'prop', { value: true, enumerable: true, writable: false, configurable: false })
const objCopy = includeKeys(obj, ['prop'])
console.log(Object.getOwnPropertyDescriptor(objCopy, 'prop'))
// { value: true, writable: true, enumerable: true, configurable: true }
```

Additionally, when a property is using `get`/`set`, they are currently removed.

```js
const obj = Object.defineProperty({}, 'prop', { get: () => Math.random(), enumerable: true })
console.log(obj.prop, obj.prop) // Different random numbers
const objCopy = includeKeys(obj, ['prop'])
console.log(objCopy.prop, objCopy.prop) // Same random numbers
```

Instead of retrieving then copying the property values, the descriptors should be used instead.

https://github.com/sindresorhus/filter-obj/blob/36e5f3a87cadeed6ef1d2da8f0362d048d3720e5/index.js#L8
https://github.com/sindresorhus/filter-obj/blob/36e5f3a87cadeed6ef1d2da8f0362d048d3720e5/index.js#L20

Note: I can submit a PR.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #20.

This ensures descriptors properties (`writable`, `configurable`, `get`, `set`) are kept when copying.
Note: we ignore non-enumerable properties, so `enumerable` is always `true`.

This is a bug fix. However, this could arguably be a breaking change for some consumers relying on the current (incorrect) behavior.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -5,26 +5,17 @@ export function includeKeys(object, predicate) {
...
-					configurable: true,
-				});
+				const descriptor = Object.getOwnPropertyDescriptor(object, key);
+				Object.defineProperty(result, key, descriptor);
 			}
 		}
 	} else {
 		// `for ... of Object.keys()` is faster than `for ... of Object.entries()`.
 		for (const key of Object.keys(object)) {
 			const value = object[key];
```
Comment (ehmicky) [inline index.js:15]: Note: `value` and `descriptor` are retrieved separately, since `descriptor.value !== value` when `descriptor.get` is present.
