### PR TITLE
Do not ignore symbol properties

### LINKED ISSUE #21: Symbol properties should be kept
The `README` documents that symbol properties are not kept. However, this leads to some behavior that users might not expect:

```js
const symbol = Symbol('example')
const obj = { [symbol]: true, a: 1, b: 2 }
const objCopy = excludeKeys(obj, ['b'])
objCopy[symbol] // undefined. Unexpected: the consumer only wanted to exclude 'b'

const objCopyTwo = includeKeys(obj, [symbol, 'a'])
objCopyTwo[symbol] // undefined. Unexpected: the consumer intended to keep symbol
```

I can submit a PR.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #21.

This ensures symbol properties are kept.
This is a breaking change since the function predicate passed as argument needs to handle the potential case that the key might be a symbol instead of a string.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -3,8 +3,8 @@ export function includeKeys(object, predicate) {
 
 	if (Array.isArray(predicate)) {
 		const set = new Set(predicate);
-		for (const key of Object.keys(object)) {
-			if (set.has(key)) {
+		for (const key of Reflect.ownKeys(object)) {
+			if (isEnumerable.call(object, key) && set.has(key)) {
```
Comment (ehmicky) [inline index.js:7]: Unlike `Object.keys()`, `Reflect.ownKeys()` also returns symbols. However, it also returns non-enumerable properties, so we need an additional check.

File: index.js [hunk 2]
```diff
@@ -15,23 +15,27 @@ export function includeKeys(object, predicate) {
...
+					});
+				}
 			}
 		}
 	}
 
 	return result;
 }
 
+const {propertyIsEnumerable: isEnumerable} = Object.prototype;
```
Comment (ehmicky) [inline index.js:37]: `propertyIsEnumerable` is also a global function, so the property is renamed to avoid shadowing.

File: readme.md [hunk 3]
```diff
@@ -48,15 +46,15 @@ The source object to filter properties from.
 
 #### filter
 
-Type: `(sourceKey, sourceValue, source) => boolean`
+Type: `(sourceKey: string | symbol, sourceValue: any, source: object) => boolean`
```
Comment (ehmicky) [inline readme.md:49]: `Reflect.ownKeys()` returns indices as strings, so `sourceKey` cannot be a `number`.

File: index.test-d.ts [hunk 4]
```diff
@@ -1,15 +1,17 @@
 import {expectType, expectError} from 'tsd';
 import {includeKeys, excludeKeys} from './index.js';
 
+const propSymbol = Symbol('test');
```
Comment (sindresorhus) [inline index.test-d.ts:4]:
```suggestion
const propertySymbol = Symbol('test');
```

File: readme.md [hunk 5]
```diff
@@ -48,15 +46,15 @@ The source object to filter properties from.
...
 
 A predicate function that determines whether a property should be filtered.
 
 #### keys
 
-Type: `string[]`
+Type: `(string | symbol)[]`
```
Comment (sindresorhus) [inline readme.md:55]:
```suggestion
Type: `Array<string | symbol>`
```

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: index.test-d.ts (hunk 4 above)
Comment (ehmicky) [reply index.test-d.ts]: Done in c4552a01e5919f9758d0cbe4080dbd4ae1b1efc0

**Comment by ehmicky** [comment]
Fixed :+1:

**Comment by sindresorhus** [comment]
Thanks :)
